name: CI
on:
  push:

jobs:
  get-commit-info:
    uses: 'justwatch/reusable_workflows/.github/workflows/get-commit-info.yml@main'

  push-docker-image:
    needs: [get-commit-info]
    uses: "justwatch/reusable_workflows/.github/workflows/build-docker-image.yml@main"
    with:
      IMAGE_NAME: ${{ github.event.repository.name }}
      IMAGE_TAG: ${{ needs.get-commit-info.outputs.Hash }}
      DOCKERFILE: Dockerfile
      PUSH: true
    secrets: inherit