name: CI
on:
  push:

jobs:
  get-commit-info:
    uses: "justwatch/reusable_workflows/.github/workflows/get-commit-info.yml@main"

  build-and-push:
    needs: [get-commit-info]
    uses: "justwatch/reusable_workflows/.github/workflows/infra_build_docker.yml@main"
    secrets: inherit
    with:
      IMAGE_NAME: ${{ github.event.repository.name }}
      IMAGE_TAG: ${{ needs.get-commit-info.outputs.Hash }}
      DOCKERFILE: Dockerfile